version: '3.8'

services:
  game_db:
    image: postgres:13
    ports:
      - 5432:5432
    env_file:
      - .env
    networks:
      - game
    volumes:
      - game_db:/var/lib/postgresql/data

networks:
  game:

volumes:
  game_db:
    driver: local
    driver_opts:
      type: none
      device: /Users/mohamedkorchi/data/gamedb
      o: bind