version: '3.8'
services:
  dev-db:
    image: postgres:13
    ports:
      - 5432:5432
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 123
      POSTGRES_DB: nest
  # backend:
    # build: 
      # context: ./backend
    # volumes:
      # - ./backend:/app
    # ports:
      # - 3000:3000
    # depends_on:
      # - dev-db
networks:
  default: