version: '3.8'
services:
  dev-db:
    image: postgres:13
    ports:
      - 5434:5432
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 123
      POSTGRES_DB: nest
    restart: always
  # backend:
    # build: 
      # context: ./backend
    # volumes:
      # - ./backend:/app
    # ports:
      # - 3000:3000
    # depends_on:
      # - dev-db
    # restart: always
  # frontend:
    # build: 
      # context: ./frontend
    # volumes:
      # - ./frontend:/app
    # ports:
      # - 5173:5173
    # depends_on:
      # - dev-db
    # restart: always
networks:
  default: